server:
  port: 8080

logging.file: logs/application.log
logging:
  level:
    org:
      springframework:
        web: DEBUG
spring:
  datasource:
    # url:  jdbc:h2:mem:tws_persistence_db;MODE=Oracle

    url:  jdbc:h2:file:~/.h2/DBName;AUTO_SERVER=TRUE
  h2:
    console:
      enabled: true
mybatis:
  mapper-locations: "classpath:mapper/*Mapper.xml"
